// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSK1LXKkYKgs1vkOvVLlzUHf6u3jgYQCI',
    appId: '1:94288131228:web:eed029c0463e15ebce2959',
    messagingSenderId: '94288131228',
    projectId: 'dues-35631',
    authDomain: 'dues-35631.firebaseapp.com',
    databaseURL: 'https://dues-35631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dues-35631.appspot.com',
    measurementId: 'G-HJ8LVTE3CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnsP3UkVUq-j1e1IF9nDj-29-L29CqO6M',
    appId: '1:94288131228:android:157fcb8e543f04b3ce2959',
    messagingSenderId: '94288131228',
    projectId: 'dues-35631',
    databaseURL: 'https://dues-35631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dues-35631.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLDyVJceq1VZgzRx3JAvNO_6-frTB2-s',
    appId: '1:94288131228:ios:a01ae58b8efed08bce2959',
    messagingSenderId: '94288131228',
    projectId: 'dues-35631',
    databaseURL: 'https://dues-35631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dues-35631.appspot.com',
    iosBundleId: 'com.example.micetalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkLDyVJceq1VZgzRx3JAvNO_6-frTB2-s',
    appId: '1:94288131228:ios:49331950f57639e5ce2959',
    messagingSenderId: '94288131228',
    projectId: 'dues-35631',
    databaseURL: 'https://dues-35631-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dues-35631.appspot.com',
    iosBundleId: 'com.example.micetalks.RunnerTests',
  );
}
